# Generated by Django 4.2.18 on 2025-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
