# Generated by Django 4.2.18 on 2025-05-26 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_fakelandingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelandingpage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fake_landing_pages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
