# Generated by Django 4.2.18 on 2025-05-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fakelandingpage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakelandingpage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
    ]
