# Generated by Django 4.2.18 on 2025-05-26 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fakelandingpage_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeLandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('fake_landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fakelandingpage')),
            ],
        ),
    ]
