# Generated by Django 4.2.18 on 2025-05-26 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fakelandingpagesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelandingpagesubmission',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakelandingpagesubmission',
            name='submitted_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
