# Generated by Django 4.2.18 on 2025-05-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fakelandingpagesubmission_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelandingpagesubmission',
            name='unique_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fakelandingpagesubmission',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='fakelandingpagesubmission',
            name='fake_landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_landing_page_submission', to='core.fakelandingpage'),
        ),
        migrations.AlterField(
            model_name='fakelandingpagesubmission',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
