# Generated by Django 4.2.18 on 2025-05-26 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_fakelandingpagesubmission_unique_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelandingpage',
            name='rid',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fakelandingpage',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='fakelandingpage',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='fakelandingpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
