# Generated by Django 4.2.18 on 2025-05-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fakelandingpage_rid_alter_fakelandingpage_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakelandingpage',
            name='original_landing_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.landingpage'),
        ),
    ]
